config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :reviews, only: [:show, :create, :edit, :destroy]
  end
  resources :users, only: [:new, :create, :show, :index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :categories, only: [:show, :new, :create, :destroy]

  root 'products#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews
	has_many :users, through: :reviews
	belongs_to :category
	validates :description, :name, presence: true
	validates :price_in_cents, numericality: {only_integer: true}

	def formatted_price
		price_in_dollars = price_in_cents.to_f / 100
		sprintf("%.2f", price_in_dollars)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	scope :newest_first, -> {order("created_at DESC")}
	validates :comment, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reviews
	has_many :products, through: :reviews
	has_secure_password
	validates :name, presence: true
	validates :email, presence: true
	validates :email, format: {with: /\@/, message: " format is incorrect. Should be your_email@domain.com"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def show
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new

	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to products_path
		else
			render :new
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to products_path
	end

	private
	def category_params
		params.require(:category).permit(:name)
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      Product.order('products.created_at DESC')
    end
    @products = @products.page(params[:page])
    @categories = Category.all

    respond_to do |format|
      format.html
      format.js
    end
  end

  def home
    @products = Product.all
    @categories = Category.all
  end

  def show
   @product = Product.find(params[:id])

   if current_user
    @review = @product.reviews.build
  end
end

def new
 @product = Product.new
end

def edit
 @product = Product.find(params[:id])
end

def create
 @product = Product.new(product_params)

 if @product.save
  redirect_to products_url
else
  render :new
end
end

def update
 @product = Product.find(params[:id])
 if @product
  @product.update_attributes(product_params)
  redirect_to product_path(@product)
else
  render :edit
end
end

def destroy
 @product = Product.find(params[:id])
 @product.destroy
 redirect_to products_path
end

private
def product_params
 params.require(:product).permit(:name, :description, :price_in_cents, :category_id)
end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product# :ensure_logged_in, only: [:create, :destroy]
  before_filter :load_review, only: [:show, :edit, :destroy, :update]

  def show
  end

  def edit
  end

  def update
    @review.update_attributes(review_params)
    if @review.save
      redirect_to @review
    else
      render :edit
    end
  end

  def create
  	@review = @product.reviews.build(review_params)
  	@review.user = current_user

    respond_to do |format|
     if @review.save
      format.html {redirect_to products_path, notice: 'Review created successfully'}
      format.js { j render :partial => 'reviews/reviews' } #This will look for app/views/reviews/create.js.erb
    else
      format.html { render 'products/show'}
      format.js { 
        j render :partial => 'reviews/review_form_errors', :status => 404
      }
    end
  end
end

def destroy
 @review.destroy
 redirect_to products_path
end

private
def review_params
 params.require(:review).permit(:comment, :product_id)
end

def load_product
 @product = Product.find(params[:product_id])
end

def load_review
  @review = @product.reviews.find(params[:id])
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_url, :notice => "Logged in!"
  	else 
  		flash.now[:alert] = "Invalid email or password"
  		render :new
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_url, notice: "Signed up!"
  	else
  		render :new
  	end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :name, :age, :url)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/new.html.erb
<h1>Create a new category</h1>


<%= form_for @category do |f| %>
<div class="field">
	<%= f.label :name %> <br />
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.submit %><br />
</div>
<% end %>

app/views/categories/show.html.erb
<h1>Categories</h1>


<!-- To select all products in all categories -->
<!-- @categories.each do |category|
	category.products.each do |product|
	end
	end -->

	<h2> <%= @category.name %> </h2>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Description</th>
				<th>Price</th>
			</tr>
		</thead>
		<% @category.products.each do |pro| %>
		<tbody>
			<tr>
				<td> <%= pro.name %> </td>
				<td> <%= pro.description %> </td>
				<td> <%= pro.price_in_cents %>$ </td>
			</tr>
		</tbody>
		<% end %>
	</table>

	<%= link_to "Delete", @category, method: :delete, data: {confirm: "Are you sure you want to delete this category?"} %>

	<%= link_to 'Back to Main Page', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Rainforest</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<!-- ----------------------------------------------------------------------------------------------- -->


	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/"><img src="http://k-slaw.blogspot.com/favicon.ico"/></a>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="/products">Main Menu</a></li>
					<li><a href="/products/new">Add a product</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="/categories/1">Electronics</a></li>
							<li><a href="/categories/4">Books</a></li>
							<li><a href="/categories/5">..</a></li>
							<!-- <li class="divider"></li>
							<li><a href="#">Separated link</a></li>
							<li class="divider"></li>
							<li><a href="#">One more separated link</a></li> -->
						</ul>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<% if current_user %> 
					<li><%= link_to current_user.name, current_user %> </li>
					<li><%= link_to "Log out", session_path("current"), :method => :delete %></li>
					<% else %>
					<!-- <li><a href="/sessions/new">Log in</a></li> -->
					<!-- Indicates a successful or positive action -->
					<a href="/sessions/new"> <button type="button" class="btn btn-success">Log in</button> </a>
					<a href="/users/new"> <button type="button" class="btn btn-success">Sign up</button> </a>
					<% end %>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>


	<!-- ----------------------------------------------------------------------------------------------- -->


	<% if flash[:notice] %>
	<p id= "notice"><%= flash[:notice] %></p>
	<% end %>
	<% if flash[:alert] %>
	<p id = "alert"><%= flash[:alert] %></p>
	<% end %>

	<%= yield %>

	<!-- <p class="userinfo">
		<% if current_user %>
		Signed in as <%= link_to current_user.name, current_user %> <%= link_to "Log out", session_path("current"), :method => :delete %>
		<% else %>
		<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
		<% end %>
	</p> -->
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id= "error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <% end %>
    </ul>
    </div>
    <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <!-- This is where i create a drop down in the new product form so i can associate the product with the category -->
  <div class="field">
  <%= collection_select(:product, :category_id, Category.all, :id, :name, prompt: true) %>
  </div>

  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_products.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Price</th>
		</tr>
	</thead>
	<tbody>
		<% @products.each do |product| %>
			<tr>
				<td><%= link_to product.name, product_path(product)%></td>
				<td><%= product.description %></td>
				<td><%= product.formatted_price %>$</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/products/edit.html.erb
<h1>Edit</h1>


<%= render 'form' %>

app/views/products/home.html.erb
<h1>Work in progress HOMEPAGE</h1>

app/views/products/index.html.erb
<h1>Main Page</h1>

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag "Search" %>
<% end %>

<div id="products">
	<%= render :partial => "products" %>
</div>

<!-- outputs several pagination links such as « First ‹ Prev ... 2 3 4 5 6 7 8 9 10 ... Next › Last » -->
<div><%= paginate @products %></div>

app/views/products/index.js.erb
<% if (params[:search]) %>
	$('#products').html("<%= j(render :partial => 'products') %> ");
<% else %>
	$('#products').append("<%= j(render :partial => 'products') %> ");
<%end%>
$('.pagination').replaceWith('<%= j paginate(@products) %>');

app/views/products/new.html.erb
<h1>Create a new product</h1>

<%= render 'form' %>

<%= link_to 'Back to Main Page', products_path %>

app/views/products/show.html.erb
<h1>Display</h1>

<p><%= @product.name %> <%= @product.description%> <%= @product.formatted_price %> </p>


<%= render :partial => 'reviews/reviews' %>
<%= render 'reviews/form_new' %>


<%= link_to "Back to Products", products_path %> | <%= link_to "Edit", edit_product_path(@product) %> | <%= link_to "Delete", @product, method: :delete, data: {confirm: "Are you sure you want to delete this product?"} %>

<%= link_to 'Back to Main Page', products_path %>

<script type="text/javascript">
	$(function() {
		$("#new_review")
        .on('ajax:beforeSend', function() { // set this code to happen just before the ajax request is made
          $("input[type='submit']") // make changes to the submit button
            .val('Saving...') // change the text on the button
            .attr('disabled', 'disabled'); // disable the button
        })
        .on('ajax:complete', function(event, data) {
        	$("input[type='submit']")
        	.val('Create Review')
        	.removeAttr('disabled');

        	//Stretch assignment. Bypassing create.js.erb

        	if ( data.status == 404 ) {
        		$("#review-form-errors").html(data.responseText);
        	} else {
        		$("#review-form-errors").html("");
        		$('#review-list').html(data.responseText);
        		$("#new_review")[0].reset();
        		$('#review').css({
        			'background-color': 'cyan'
        		});
            }
        });
    });
</script>

app/views/reviews/_form_new.html.erb
<h4>New Review</h4>

<% if current_user %>
	<%= form_for [@product, @review], :remote => true do |f| %>
		<%= render :partial => 'reviews/review_form_errors' %>

		<div class="field">
		  <%= f.label :comment %><br />
		  <%= f.text_area :comment %>
		</div>

		<div class="actions">
		  <%= f.submit %>
		</div>
	<% end %>

<% else %>
	<p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %>

app/views/reviews/_review_form_errors.html.erb
<div id="review-form-errors">
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/reviews/_reviews.html.erb
<div id="review-list">
	<h3>Reviews</h3>

	<div id="poster">
		<p>Reviews for <%= @product.name %></p>
	</div>

	<% @product.reviews.newest_first.each do |review| %>
		<p id='review'>
			<%= review.comment %>
			<br>
			<% if review.user != nil %>
				<em> by <%= link_to review.user.email, user_url(review.user) %></em>
				Added on: <%= review.created_at %>
			<% end %>
		</p>
	<% end %>
</div>

app/views/reviews/edit.html.erb
<%= render 'form' %>

app/views/reviews/new.html.erb
<%= render 'form_new' %>

app/views/reviews/show.html.erb
<h1>Review</h1>
<p> <%= @review.comment %> </p>
<p>For product:</p> <p> <%= @product.name %></p>

<p> <%= link_to "Delete Product", product_review_path, method: :delete, data: {confirm: "Are you sure you want to delete"} %> <p>

<%= link_to "Edit", edit_product_review_path(@product, @review) %>

<%= link_to "Back", products_path %>

app/views/users/_form.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div class="error_messages">
  <h2>Form is invalid</h2>
  <ul>
    <% for message in @user.errors.full_messages %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :email %><br/>
  <%= f.text_field :email %>
</div>

<div class="field">
  <%= f.label :age %><br/>
  <%= f.number_field :age %>
</div>

<div class="field">
    <%= f.label :picture_Url %><br/>
    <%= f.text_field :url %>
  </div>

<div class="field">
  <%= f.label :password %><br/>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %><br/>
  <%= f.password_field :password_confirmation %>
</div>
<div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @user.each do |user| %>
	<ul>
	<li> <%= user.name %> <%= link_to "Delete", user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete"} %> </li>
	</ul>
	<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/new_html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Profile page</h1>

<img src="<%= @user.url %>">

<p>Email: <%= @user.email %> </p>
<p>Name: <%= @user.name %> </p>
<p>Age: <%= @user.age %> </p>

<%= link_to "Back to main page", products_path %>